const express=require('express'),http=require('http'),{Server}=require('socket.io');
const {createClient}=require('@supabase/supabase-js');
const app=express(),srv=http.createServer(app),io=new Server(srv);
app.use(express.static('public'));app.get('/health',(q,r)=>r.send('ok'));
const ADMIN=process.env.ADMIN_PASS||'admin';
const sb=process.env.SUPABASE_URL?createClient(process.env.SUPABASE_URL,process.env.SUPABASE_KEY):null;
let S={teams:{},items:[],sug:[],round:null,bids:{},results:null,n:1};
const seed=()=>{S.items=['React','Vue','Angular','Next.js','Tailwind CSS','Bootstrap','Node.js','Express','MongoDB','Firebase','GitHub','Figma','Vercel','Vite','TypeScript'].map(name=>({id:S.n++,name}))};
let tm;const save=()=>{clearTimeout(tm);tm=setTimeout(()=>sb&&sb.from('auction_state').upsert({id:1,data:S}).then(r=>r.error&&console.log(r.error.message)),500)};
const isOpen=()=>S.round&&Date.now()<S.round.endsAt;
const nm=id=>(S.items.find(i=>i.id===+id)||{}).name||'?';
const sum=o=>Object.values(o||{}).reduce((a,b)=>a+b,0);
const won=t=>S.results?Object.values(S.results).filter(r=>r.w.includes(t)).reduce((a,r)=>a+r.a,0):0;
const left=t=>S.teams[t].budget-(S.results?won(t):sum(S.bids[t]));
const roundInfo=()=>isOpen()?{name:nm(S.round.id),endsAt:S.round.endsAt}:null;
const resList=()=>S.results&&Object.entries(S.results).map(([id,r])=>({name:nm(id),w:r.w,a:r.a}));
const teamView=t=>({left:left(t),round:roundInfo(),mine:Object.entries(S.bids[t]||{}).map(([id,a])=>({name:nm(id),a})),res:resList()});
const adminView=()=>{const cnt={};for(const t in S.bids)for(const id in S.bids[t])cnt[id]=(cnt[id]||0)+1;
 return {teams:S.teams,items:S.items,sug:S.sug,round:roundInfo(),cnt,res:resList(),bids:S.bids}};
function bc(){for(const [,s] of io.sockets.sockets){let v;
 if(s.data.admin)v=adminView();else if(s.data.team&&S.teams[s.data.team])v=teamView(s.data.team);else continue;
 const k=JSON.stringify(v);if(k!==s.data.k){s.data.k=k;s.emit('state',{...v,now:Date.now()})}}}
io.on('connection',sock=>{
 const A=f=>(...a)=>{if(sock.data.admin){f(...a);save();bc()}};
 sock.on('join',({name,code},cb)=>{name=String(name||'').trim();const t=S.teams[name];
  if(!t||t.code!==String(code||'').trim())return cb(false);sock.data={team:name};cb(true);bc()});
 sock.on('admin',(p,cb)=>{if(p!==ADMIN)return cb(false);sock.data={admin:true};cb(true);bc()});
 sock.on('bid',({amount},cb)=>{const t=sock.data.team;amount=Math.floor(+amount);
  if(!t||S.results)return cb('Bidding is closed');if(!isOpen())return cb('No round is open');
  if(!(amount>0))return cb('Enter a valid amount');
  const id=S.round.id,b=S.bids[t]=S.bids[t]||{};
  const others=Object.entries(b).filter(([k])=>+k!==id).reduce((a,[,v])=>a+v,0);
  if(others+amount>S.teams[t].budget)return cb('Over budget. Max for this item: '+(S.teams[t].budget-others));
  b[id]=amount;save();cb('Bid saved: '+amount);bc()});
 sock.on('suggest',x=>{if(sock.data.team&&!S.results&&S.sug.length<50){S.sug.push(String(x).trim().slice(0,40));save();bc()}});
 sock.on('addTeam',A(({name,code,budget})=>{name=String(name).trim();if(name&&code)S.teams[name]={code:String(code).trim(),budget:Math.floor(+budget)||100000}}));
 sock.on('delTeam',A(n=>{delete S.teams[n];delete S.bids[n]}));
 sock.on('addItem',A(n=>{n=String(n).trim();if(n)S.items.push({id:S.n++,name:n})}));
 sock.on('delItem',A(id=>{S.items=S.items.filter(i=>i.id!==id)}));
 sock.on('addSug',A(i=>{const n=S.sug.splice(i,1)[0];if(n)S.items.push({id:S.n++,name:n})}));
 sock.on('delSug',A(i=>{S.sug.splice(i,1)}));
 sock.on('open',A(({id,secs})=>{if(S.results)return;secs=Math.max(5,+secs||60);S.round={id,endsAt:Date.now()+secs*1000};setTimeout(bc,secs*1000+300)}));
 sock.on('close',A(()=>{if(S.round)S.round.endsAt=Date.now()}));
 sock.on('reveal',A(()=>{S.round=null;S.results={};
  for(const it of S.items){let m=0,w=[];for(const t in S.bids){const a=S.bids[t][it.id]||0;if(a>m){m=a;w=[t]}else if(a&&a===m)w.push(t)}
   if(m)S.results[it.id]={w,a:m}}}));
 sock.on('reset',A(()=>{S.bids={};S.results=null;S.round=null}));
});
(async()=>{let ok=false;try{if(sb){const {data}=await sb.from('auction_state').select('data').eq('id',1).maybeSingle();if(data){S=data.data;ok=true}}}catch(x){console.log(x.message)}
 if(!ok)seed();srv.listen(process.env.PORT||3000,()=>console.log('up'))})();
